name: Release pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: 'Build and Release'
    runs-on: windows-2019
    env:
      XDG_CACHE_HOME: tmp/pip
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          # GFEConnector собран под 32bit
          architecture: x86
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Build
        run: |
          python -m pip install --upgrade pip poetry
          poetry install
          poetry run pytest
          poetry build
      - name: Create binary
        run: |
          poetry run pyinstaller src/gfe_devices_grabber/main.py --name "gfe-devices-grabber" --specpath src/ --windowed --onefile --noconfirm
      - name: Release
        shell: bash
        run: |
          mv ./dist/*.whl ./dist/gfe-devices-grabber.whl
          gh release create ${{ github.ref_name }} ./dist/gfe-devices-grabber.whl ./dist/gfe-devices-grabber.exe
